---
title: "Homework #1 (Population Genomics)"
output:
  prettydoc::html_pretty:
    theme: cayman
fontsize: 18pt
---

# Homework assignment #1 -- Due by Thursday October 09, 2025 (end of day)

We’ve now completed our first module of coding sessions. Let's review all you've learned!

* *How to log in and move around a Unix server and the VACC OOD interface*
* *How to write bash scripts and execute them at the command line*
* *How to submit jobs via SLURM and sbatch to the cluster*
* *Working with raw Illumina NGS data, from QC to read trimming to mapping to a reference genome*
* *Using the ANGSD pipeline to analyze low-coverage sequencing for estimates of nucleotide diversity, Tajima's D, and Fst*
* *Estimating and visualizing population structure in the form of genetic PCA and admixture plots*
* *Testing for selection using outlier analyses (PCAngsd)*

You've accomplished a lot! :)

Along the way, we've learned and discussed what these results mean for the genetic history of red spruce and its adaptation. 

**The picture that is emerging is one of complex population structure in the north vs. south part of the range, but also clear evidence of hybridization in different areas that also correspond with selection acting along those gradients of population structure.** 

## Your first homework assignment is to more fully explore these results by choosing ONE of the options below:

(a) ***Option A: Sensitivity of nucleotide diversity and Tajima's D to different filtering strategies.***

To address this question, you'll want to look back at the ANGSD filters we used when we first called the genotype likelihoods in preparation for estimating nucleotide diversity (Tutorial 3). Choose **any 2** of the following filters, read about them on the ANGSD manual page, and **choose 2 different values** of each filter to explore. You should do each new filtering value on its own without changing any of the other values (total of 4 runs). Then choose 1 additional run where you change 2 of the filtering options at the same time.  The filters you can choose among are:

* remove_bads
* minInd
* setMinDepthInd
* setMaxDepthInd
* skipTriallelic

For each new run you do with changed filter parameters, calculate nucleotide diversity (Pi and theta-W) and Tajima's D using ANGSD just like we did in class.  Then synthesize the results from each run in terms of the number of sites/contig, estimated nucleotide diversity and Tajima's D, and compare across the different filter options.  Were the results robust to the different values you chose?  Which do you think are most reliable and why?

(b) ***Option B: Testing for additional genetic structure and ancestry at higher levels of K***

To address this question, you'll want to look at several different values of K and run separate models for each one to investigate how it affects our interpretation of the population structure within our sampling.  You can choose to run your evaluation on just the 95 red spuce samples or the combined red + black spruce samples (N=113).  Test from K=2 to K=5. Summarize the results in terms of how much the variance explained by the eigenvalues change. You may also find it interesting to look at how the likelihood score of the overall model fit changes -- this can be gleaned from the end of the log file of the PCAngsd run. (Note, Likelihood values are usually negative, and less negative values = better fit to the data). Lastly, create Admixture plots for each level of K and compare the inference of genetic structure across the different levels.  How does this relate to the geography of the sample populations, and the contribution of hybridization from black spruce?

(c) ***Option C: Layers of evidence for selection***

To address this question, you'll want to compare selection outliers from PCAngsd (outliers on PC1 and PC2) to estimates of nucleotide diversity (Pi) and Tajima's D to see if there's evidence for selective sweeps.  To do this, you'll need to figure out which contigs harbor selection outliers from PC1 and PC2 (separately) and then look for overlap in which contigs show either strongly negative D (using a threshold of -1.5) or very low nucleotide diversity (using a threshold of tPsite<0.001).  You should base your estimation of nucleotide diversity on the entire set of 95 red spruce samples!  That will mean running ANGSD again to estimate genotype likelihoods and thetas for all 95 samples, not just your pop!  Summarize the final results with interesting figures/tables, include one or more Venn diagrams.  Refer to code at end of Tutorial 6 to help you with generating lists of outliers for investigating overlaps and plotting Venn diagrams.


# Criteria:

* The main text of the write-up should be 2 pages (max) single spaced. Tables, figures, and references can be on separate pages.
* You may work collaboratively, but the final product and all of the writing should be your own defensible work
* Approach the writing as a technical report based on the work you’ve done to date.  That is, write for a scientific audience using appropriate technical language and narrative style, with citations used when referring to methods or making factual assertions.
* Your write-up should include the following essential elements:

#### Background (1-2 paragraphs):
* A brief description providing context and motivation of the problem we’re trying to address with these data. *Capblancq et al. (2020) Evolutionary Applications* and *Capblancq et al. (2023) New Phytologist* are excellent resources for this information.
* Brief background on the study species, Geographic sampling, library prep, and sequencing strategy (look through early tutorials for info, plus your notes from class)
* A celar statement of the question you're trying to address.

#### Bioinformatics Pipeline (~2 paragraphs):
* Detailed description of the various steps you used for the analysis of the sequencing data.  Take it from QC assessment of the raw reads up to estimation of population structure and selection. You **DO NOT** need to include analyses or steps that aren't relevant to your specific analysis for this homework.
* This will section should demonstrate both your technical knowledge of the flow of the different steps in the pipeline, and your level of proficiency in understanding why each step was done.  Include justification for using particular analysis approaches or choices as appropriate (e.g., Why did we map to a reduced ref instead of the entire *P. marianca* reference genome?; Why did we use genotype likelihoods with ANGSD instead of analyzing “hard called” genotypes?, etc...).

#### Results (1-2 paragraphs)
* Report your findings from the different analysis steps.  Use a combination of reporting results in-line in your text and summarizing more detailed information in tables and/or figures.  
* You may use a max of 3 tables/figures total (not counted towards the page limit). 
* Be sure each table/figure has a title, and a very brief legend describing its contents. Table legends go **above** tables while figure legends go **below** figures.

#### Conclusion (1-2 paragraphs)
* Give your biological conclusion so far from the data: What did you learn from your analysis about the diversity, genetic structure, or selection in red spruce as it relates to your question? Be sure you relate back to your motivation given in the Background section.
* Discuss any caveats or uncertainties that should be considered when interpreting the biological conclusions.
* Discuss any methodological challenges encountered along the way that are relevant to your results and their interpretation.
* Discuss opportunities for future directions.

#### References (listed on a separate page)
* Cite papers in APA format.  Example:  

*Capblancq, T., Butnor, J. R., Deyoung, S., Thibault, E., Munson, H., Nelson, D. M., ... & Keller, S. R. (2020). Whole‐exome sequencing reveals a long‐term decline in effective population size of red spruce (Picea rubens). Evolutionary Applications, 13(9), 2190-2205.*


* Only include references to papers you cite in your text

* Github:  Have your github lab notebook up to date. Make sure any scripts used for your analysis are available in your github `myscripts` folder. Create a single Rmarkdown to process all your results and save in your `mydocs` folder. Have a dedicated entry in your popgen_notes.md notebook documenting your notes for yourself about your workflow and decisions made. 


### Guidelines and deadlines:

* You may collaborate with each other to discuss details and share notes, but your write-up should be done independently and represent your own work.  

* Due by Thursday Oct 09, 2025 (end of day)

* Reminder about AI use (excerpted from the syllabus):

●	Disclosure: Any AI use must be disclosed in a brief statement at the end of each assignment (e.g., “I used ChatGPT to help debug this part of my R script and to suggest alternate phrasing in paragraph 3.”).
●	Accountability: Students are responsible for understanding and being able to explain all code and text in their assignments, whether produced by AI or not.
●	Writing assignments: Homework and final project papers must be written by you or members of your group. AI may be used for grammar and style editing, but not for generating substantive content.
●	Misuse: Undisclosed or excessive reliance on AI that undermines demonstration of your own learning will be considered academic misconduct.


### Submission:

* Upload your homework in doc or pdf format to the Brightspace page. :


### Advice and hints :)
 
* You do **NOT** need to run everything starting from step 1.  Think carefully about what scripts you really need to run before you start and don't spend time on running analyses that aren't relevant to your specific question.

* Think about when you want to work with all the RS samples vs. RS + BS samples vs. just your "MYPOP" population.

* If you use the R code from the tutorials for plotting PCA or admixture, you'll probably need to tweak some of the plot settings (e.g., which PC axes are getting plotted), colors, axis labels and plot titles, etc. Ask for help if you're unfamiliar with plotting in R.


#### Reach out via email or office hours if you get stuck, and don't forget to have fun with it!

