---
title: "P/BIO381 Tutorials: Working with RNA-seq data"
date: 'September 29, 2021'
output:
  prettydoc::html_pretty:
    theme: cayman
fontsize: 18pt
---

# Learning Objectives for today (and for the rest of the RNAseq module!)

1. Review _Acartia husdonica_ ecology and biogeography and the experimental evolution/transcriptomics experimental design.
2. Articulate the questions we can address and hypotheses we can test with this experimental design.
3. Understand the general work flow or "pipeline" for processing and analyzing RNAseq data.
4. Learn how to make/write a bash script and how write a script to process files in batches.
5. Visualize and interpret Illumina data quality (Run FastQC on raw and cleaned reads).
6. Start _de novo_ transcriptome assembly using Trinity.
7. Start mapping reads and quantifying abundance simultaneously using [Salmon](https://www.nature.com/articles/nmeth.4197).
8. Import quant.sf files generated by Salmon into DESeq2 for analysis and visualization.
9. Start mapping reads for single nucleotide polymorphism (SNP) identification. 
10. Estimate allele frequencies and test for genetic differention.
11. Add to your growing list of bioinformatics tricks (take notes!).


## 1. Acartia hudsonica experimental evolution RNAseq experiment

_Acartia hudsonica_ is a calanoid copepod and is the cold-water-adapted sister species to _Acartia tonsa_, the copepod we read about this week in [Brennan et al.](https://www.biorxiv.org/content/10.1101/2020.01.29.925396v3). It is an estuarine and near-shore coastal species and is most abundant along the New England coast (ME, NH, MA, RI, CT), generally not further south than the Chesapeake Bay and not further north than Laborador/Newfoundland, Canada. Both Acartiid species play critical roles in ecosystem functioning at the base of the food chain as a primary consumers of phytoplankton and as a main prey item for many larval fish, including economically important fisheries. Not surprisingly, given faster development rates in warmer temperatures, studies have found a trend of body sizes decreases over the 70 years ([Rice, Dam & Stewart (2015)](https://link.springer.com/article/10.1007%2Fs12237-014-9770-0)).

In the present study, we experimentally evolved _Acartia hudsonica_ to four sets of conditions: 
  1. ocean acidification (1000 micro-atm pCO2, ambient temperature, 13 degrees C)
  2. ocean warming (15 degrees C, 400 micro-atm pCO2)
  3. combined ocean acidification and warming (1000 micro-atm pCO2, 15 degrees C)
  4. ambient (13 degrees C, 400 micro-atm pCO2)

Animals were collected from the Long Island Sound, CT and reared in the lab for 3 generations before the start of the experiment. For each treatment, there were three replicate vessels with ~4,000 individuals per vessel. To sample for RNA, pools of 50 adults were taken at the end of the F0, F2, F4, and F11 generations. Water was removed and animals were flash frozen in liquid nitrogen. RNA was extracted using a modified TRIzol extraction protocol. Library preparation and sequencing was carried out by Novogene using standard Illumina RNAseq library prep protocols. Samples were sequenced 150 base pair paired-end reads (2 x 150bp) using the Novoseq 6000 platform (Illumina's next greatest sequencer after the HiSeq 4000) with >6 Gb (gigabase pairs, equivalent to >6 billion base pairs) per sample.  

  
### Realized sample replication after sequencing:  N=38 x 2 = 76 (left and right reads)

|Trt        | Generation  |Nreps  |
|-----------|-------------|-------|
|Ambient (AA)    |F0      |3      |
|Ambient (AA)    |F2      |2      |
|Ambient (AA)    |F4      |3      |
|Ambient (AA)    |F11     |3      |
|Acidification (AH)    |F0       |3      |
|Acidification (AH)    |F2       |3      |
|Acidification (AH)    |F4      |3      |
|Warming (HA)       |F0      |3      |
|Warming (HA)       |F2      |3      |
|Warming (HA)       |F4      |3      |
|Acidification+Warming (HH)    |F0      |3     |
|Acidification+Warming (HH)    |F4      |3    |
|Acidification+Warming (HH)    |F11     |3    |
|-----------|-------------|-------|
|Total      |             |38     |

In `/data/project_data/RNAseq/rawdata/`, there should be 76 files: N=38 x 2 = 76 (left and right reads, `_1.fq.gz`, `_2.fq.gz`)


## What questions can we ask or hypotheses can we test with this experimental design, with these data?
1.
2.
3.
4.
5.
...


## Data Processing Pipeline:

* FastQC on raw reads --> Trimmomatic (trim based on base pair quality scores and clip adapter sequences) --> FastQC on cleaned reads
* Generate a reference transcriptome assembly using [Trinity](https://github.com/trinityrnaseq/trinityrnaseq/wiki)
* Evaluate transcriptome assembly for quality (length and completeness); Collapse isoforms to make a reference transcriptome.
* **For gene expression analyses:**
  * Use [Salmon](https://salmon.readthedocs.io/en/latest/salmon.html) to simulateously map reads to reference transcriptome and quantify abundance.
  * [Import](https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#3%E2%80%99_tagged_rna-seq) the data into [DESeq2](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) in R for data normalization, visualization, and statistical tests for differential gene expression.
* **For allele frequency analyses:**
  * Map cleaned reads to reference transcriptome using BWAmem
  * Identify sequence variants (SNPs) using VarScan; filter for quality, MAF, biallelic, coverage.
  * Visualize variation with PCA.
  * Identify alleles with consistent changes in allele frequency between groups using CMH statistic.


### Choose samples to visualize for quality (FastQC) and clean (Trimmomatic)

There are 13 groups of samples (based on the table above, 13 treatment x generation combinations). If every student takes one group to process, that should work out... This time we need to trim using the same specifications.
 
### FastQC
Recall that .fastq (or .fq) files are sequence data files that include quality scores for each base pair. We checked out the reads from our 16S data using `zcat FILENAME.fq.gz | head -n 4`. Recall that letters early in the alphabet indicate good quality on the ASCII score ([see Day 1 microbiome tutorial](2021-09-13_microbiome_Day1.html)). How can we look at the quality more systematically for all reads in the file?  We can use [the program FastQC](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/) (also already installed in our `/data/popgen/` directory and available to run from any directory).

FastQC will accept multiple file names as input, so figure out which letters in the filename plus a wildcard (*) will capture just the files of your group of samples.

```
fastqc FILENAME*.fq.gz --outdir=/data/project_data/RNAseq/fastqc/
```

Now move the .html files to your local machine using your favorite file transfer method (WinSCP, Fetch, scp, etc.). Open the html file by double clicking and you should see your FastQC report! (one for each file)


### Clean the reads with Trimmomatic (ALREADY DONE THIS TIME)

[Here's a link to the Trimmomatic program](http://www.usadellab.org/cms/index.php?page=trimmomatic) that we'll use to clean the reads for each file. The program is already installed in our `/data/popgen/` directory.

Already done, but for your reference, let's walk through the script:
```trim_loop.sh
#!/bin/bash   
 
# Below is a script to loop through the files in the /rawdata directory, identify matches,  
# and clean the fastq files, and direct output to /cleandata 
 
cd /data/project_data/RNAseq/rawdata
 
for f1 in *_1.fq.gz  
 
do 
 
 f2=${f1%%_1.fq.gz}"_2.fq.gz"  
 
java -classpath /data/popgen/Trimmomatic-0.39/trimmomatic-0.39.jar org.usadellab.trimmomatic.TrimmomaticPE \
        -threads 10 \
        -phred33 \
         "$f1" \
         "$f2" \
         /data/project_data/RNAseq/cleandata/"$f1"_left_clean_paired.fq \
         /data/project_data/RNAseq/cleandata/"$f1"_left_clean_unpaired.fq \
         /data/project_data/RNAseq/cleandata/"$f2"_right_clean_paired.fq \
         /data/project_data/RNAseq/cleandata/"$f2"_right_clean_unpaired.fq \
        ILLUMINACLIP:/data/popgen/Trimmomatic-0.39/adapters/TruSeq3-PE.fa:2:30:10 \
        LEADING:20 \
        TRAILING:20 \
        SLIDINGWINDOW:6:20 \
        MINLEN:36 
>> log.txt
 
done 
```
### Run FastQC on the clean reads to confirm improvement

  * What do we look for in this second run?
  * [MULTIQC](https://multiqc.info/docs/) is a tool to generate a single summary html report file from all the fastqc reports generated.
  
## Start de novo transcriptome assembly using Trinity
Okay! Now that we know we have good quality, cleaned data to work with, we can move into making a de novo transcriptome assembly, which we will "map" to twice! - once to measure gene expression and once to identify genetic variants! This is a critical step for any species without a reference genome or transcriptome and is quite easy with the trinity package. The hardest parts come after the assembly: 1) settling on a final assembly - selecting a representative sequence among isoforms and 2) annotating the genes - figuring out what they are based on homology using BLAST.

Trinity has remained at the "top of the market" for de novo transcriptome assemblers for the last 10 years. A [recent review](https://academic.oup.com/gigascience/article/8/5/giz039/5488105) finds this assembler performs consistently well across their (somewhat limited) range of datasets.

[Here's a link to the Trinity website](https://github.com/trinityrnaseq/trinityrnaseq/wiki)

Here's the basic command to run Trinity:
``
Trinity --seqType fq --left reads_1.fq --right reads_2.fq --CPU 6 --max_memory 20G 
``

Specifically, for our data: (BUT WE DON'T ALL NEED TO DO THIS!)
```
/data/popgen/trinityrnaseq-v2.13.2/Trinity --seqType fq \
--left AA_F0_Rep1_2_right_clean_paired.fq,AA_F0_Rep2_2_right_clean_paired.fq,AA_F0_Rep3_2_right_clean_paired.fq,AA_F11_Rep1_2_right_clean_paired.fq,AA_F11_Rep2_2_right_clean_paired.fq,AA_F11_Rep3_2_right_clean_paired.fq,AA_F2_Rep2_2_right_clean_paired.fq,AA_F2_Rep3_2_right_clean_paired.fq,AA_F4_Rep1_2_right_clean_paired.fq,AA_F4_Rep2_2_right_clean_paired.fq,AA_F4_Rep3_2_right_clean_paired.fq,AH_F0_Rep1_2_right_clean_paired.fq,AH_F0_Rep2_2_right_clean_paired.fq,AH_F0_Rep3_2_right_clean_paired.fq,AH_F2_Rep1_2_right_clean_paired.fq,AH_F2_Rep2_2_right_clean_paired.fq,AH_F2_Rep3_2_right_clean_paired.fq,AH_F4_Rep1_2_right_clean_paired.fq,AH_F4_Rep2_2_right_clean_paired.fq,AH_F4_Rep3_2_right_clean_paired.fq,HA_F0_Rep1_2_right_clean_paired.fq,HA_F0_Rep2_2_right_clean_paired.fq,HA_F0_Rep3_2_right_clean_paired.fq,HA_F2_Rep1_2_right_clean_paired.fq,HA_F2_Rep2_2_right_clean_paired.fq,HA_F2_Rep3_2_right_clean_paired.fq,HA_F4_Rep1_2_right_clean_paired.fq,HA_F4_Rep2_2_right_clean_paired.fq,HA_F4_Rep3_2_right_clean_paired.fq,HH_F0_Rep1_2_right_clean_paired.fq,HH_F0_Rep2_2_right_clean_paired.fq,HH_F0_Rep3_2_right_clean_paired.fq,HH_F11_Rep1_2_right_clean_paired.fq,HH_F11_Rep2_2_right_clean_paired.fq,HH_F11_Rep3_2_right_clean_paired.fq,HH_F4_Rep1_2_right_clean_paired.fq,HH_F4_Rep2_2_right_clean_paired.fq,HH_F4_Rep3_2_right_clean_paired.fq \
--right AA_F0_Rep1_1_left_clean_paired.fq,AA_F0_Rep2_1_left_clean_paired.fq,AA_F0_Rep3_1_left_clean_paired.fq,AA_F11_Rep1_1_left_clean_paired.fq,AA_F11_Rep2_1_left_clean_paired.fq,AA_F11_Rep3_1_left_clean_paired.fq,AA_F2_Rep2_1_left_clean_paired.fq,AA_F2_Rep3_1_left_clean_paired.fq,AA_F4_Rep1_1_left_clean_paired.fq,AA_F4_Rep2_1_left_clean_paired.fq,AA_F4_Rep3_1_left_clean_paired.fq,AH_F0_Rep1_1_left_clean_paired.fq,AH_F0_Rep2_1_left_clean_paired.fq,AH_F0_Rep3_1_left_clean_paired.fq,AH_F2_Rep1_1_left_clean_paired.fq,AH_F2_Rep2_1_left_clean_paired.fq,AH_F2_Rep3_1_left_clean_paired.fq,AH_F4_Rep1_1_left_clean_paired.fq,AH_F4_Rep2_1_left_clean_paired.fq,AH_F4_Rep3_1_left_clean_paired.fq,HA_F0_Rep1_1_left_clean_paired.fq,HA_F0_Rep2_1_left_clean_paired.fq,HA_F0_Rep3_1_left_clean_paired.fq,HA_F2_Rep1_1_left_clean_paired.fq,HA_F2_Rep2_1_left_clean_paired.fq,HA_F2_Rep3_1_left_clean_paired.fq,HA_F4_Rep1_1_left_clean_paired.fq,HA_F4_Rep2_1_left_clean_paired.fq,HA_F4_Rep3_1_left_clean_paired.fq,HH_F0_Rep1_1_left_clean_paired.fq,HH_F0_Rep2_1_left_clean_paired.fq,HH_F0_Rep3_1_left_clean_paired.fq,HH_F11_Rep1_1_left_clean_paired.fq,HH_F11_Rep2_1_left_clean_paired.fq,HH_F11_Rep3_1_left_clean_paired.fq,HH_F4_Rep1_1_left_clean_paired.fq,HH_F4_Rep2_1_left_clean_paired.fq,HH_F4_Rep3_1_left_clean_paired.fq \
--CPU 10 --max_memory 20G 
```
Note: We'll provide the path to the latest version of Trinity just out this month (Sept 2021) and installed, just to make sure we're using the latest version. It's a little "messier", but it also helps us keep track of what version of the program we used.


Let's explore some some of the [assembly quality assessment tools that Trinity provides](https://github.com/trinityrnaseq/trinityrnaseq/wiki/Transcriptome-Assembly-Quality-Assessment).



